INSERT INTO user_types(Name) VALUES
('Administrator'), ('Business'), ('User');

INSERT INTO users (EmailAddress, Password, FirstName, LastName, UserTypeId, TimeOfRegistration, IsVerified) VALUES
('admin', '$2y$12$XMcSoI8o6/m8iaodVsdkt.G4OVmNWftRjim2OUSE/RQ2nivqpM8/S', 'Admin', '', 1, '1900-01-01 00:00:00', 1);

INSERT INTO cities (CityName, IsMainCity) VALUES
('Sofia',true),
('Plovdiv',true),
('Varna',true),
('Burgas',true),
('Ruse',true),
('Stara Zagora',true),
('Pleven',true),
('Veliko Tarnovo',true),
('Bansko',true),
('Blagoevgrad',true),
('Aheloy',false),
('Ahtopol',false),
('Aksakovo',false),
('Alfatar',false),
('Antonovo',false),
('Apriltsi',false),
('Ardino',false),
('Asenovgrad',false),
('Aytos',false),
('Balchik',false),
('Balgarovo',false),
('Bankya',false),
('Banya',false),
('Batak',false),
('Batanovtsi',false),
('Belene',false),
('Belitsa',false),
('Belogradchik',false),
('Beloslav',false),
('Belovo',false),
('Berkovitsa',false),
('Boboshevo',false),
('Bobov Dol',false),
('Bolyarovo',false),
('Borovo',false),
('Botevgrad',false),
('Boychinovtsi',false),
('Bozhurishte',false),
('Bratsigovo',false),
('Bregovo',false),
('Breznik',false),
('Brezovo',false),
('Brusartsi',false),
('Buhovo',false),
('Byala (Rousse)',false),
('Byala (Varna)',false),
('Byala Cherkva',false),
('Byala Slatina',false),
('Chepelare',false),
('Chernomorets',false),
('Cherven Bryag',false),
('Chiprovtsi',false),
('Chirpan',false),
('Dalgopol',false),
('Debelets',false),
('Devin',false),
('Devnya',false),
('Dimitrovgrad',false),
('Dimovo',false),
('Dobrich',false),
('Dobrinishte',false),
('Dolna Banya',false),
('Dolna Mitropoliya',false),
('Dolna Oryahovitsa',false),
('Dolni Chiflik',false),
('Dolni Dabnik',false),
('Dospat',false),
('Dragoman',false),
('Dryanovo',false),
('Dulovo',false),
('Dunavtsi',false),
('Dupnitsa',false),
('Dve Mogili',false),
('Dzhebel',false),
('Elena',false),
('Elhovo',false),
('Elin Pelin',false),
('Etropole',false),
('Gabrovo',false),
('Galabovo',false),
('General Toshevo',false),
('Glavinitsa',false),
('Glodzhevo',false),
('Godech',false),
('Gorna Oryahovitsa',false),
('Gotse Delchev',false),
('Gramada',false),
('Gulyantsi',false),
('Gurkovo',false),
('Hadzhidimovo',false),
('Harmanli',false),
('Haskovo',false),
('Hisarya',false),
('Ignatievo',false),
('Ihtiman',false),
('Iskar',false),
('Isperih',false),
('Ivaylovgrad',false),
('Kableshkovo',false),
('Kalofer',false),
('Kameno',false),
('Kaolinovo',false),
('Kardzhali',false),
('Karlovo]',false),
('Karnobat',false),
('Kaspichan',false),
('Kavarna',false),
('Kazanluk',false),
('Kermen',false),
('Kilifarevo',false),
('Kiten',false),
('Klisura',false),
('Knezha',false),
('Kocherinovo',false),
('Koprivshtitsa',false),
('Kostandovo',false),
('Kostenets',false),
('Kostinbrod',false),
('Kotel',false),
('Koynare',false),
('Kozloduy',false),
('Kran',false),
('Kresna',false),
('Krichim',false),
('Krivodol',false),
('Krumovgrad',false),
('Kubrat',false),
('Kuklen',false),
('Kula',false),
('Kyustendil',false),
('Laki',false),
('Letnitsa',false),
('Levski',false),
('Lom',false),
('Lovech',false),
('Loznitsa',false),
('Lukovit',false),
('Lyaskovets',false),
('Lyubimets',false),
('Madan',false),
('Madzharovo',false),
('Maglizh',false),
('Malko Tarnovo',false),
('Marten',false),
('Melnik',false),
('Merichleri',false),
('Mezdra',false),
('Miziya',false),
('Momchilgrad',false),
('Momin Prohod',false),
('Montana',false),
('Nedelino',false),
('Nesebar',false),
('Nikolaevo',false),
('Nikopol',false),
('Nova Zagora',false),
('Novi Iskar',false),
('Novi Pazar',false),
('Obzor',false),
('Omurtag',false),
('Opaka',false),
('Oryahovo',false),
('Panagyurishte',false),
('Parvomay',false),
('Pavel Banya',false),
('Pavlikeni',false),
('Pazardzhik',false),
('Pernik',false),
('Perushtitsa',false),
('Peshtera',false),
('Petrich',false),
('Pirdop',false),
('Plachkovtsi',false),
('Pliska',false),
('Polski Trambesh',false),
('Pomorie',false),
('Popovo',false),
('Pordim',false),
('Pravets',false),
('Primorsko',false),
('Provadiya',false),
('Radnevo',false),
('Radomir',false),
('Rakitovo',false),
('Rakovski',false),
('Razgrad',false),
('Razlog',false),
('Rila',false),
('Roman',false),
('Rudozem',false),
('Sadovo',false),
('Saedinenie',false),
('Samokov',false),
('Sandanski',false),
('Sapareva Banya',false),
('Sarnitsa',false),
('Senovo',false),
('Septemvri',false),
('Sevlievo',false),
('Shabla',false),
('Shipka',false),
('Shivachevo',false),
('Shumen',false),
('Silistra',false),
('Simeonovgrad',false),
('Simitli',false),
('Slavyanovo',false),
('Sliven',false),
('Slivnitsa',false),
('Slivo Pole',false),
('Smolyan',false),
('Smyadovo',false),
('Sopot',false),
('Sozopol',false),
('Sredets',false),
('Stamboliyski',false),
('Straldzha',false),
('Strazhitsa',false),
('Strelcha',false),
('Sungurlare',false),
('Suvorovo',false),
('Sveti Vlas',false),
('Svilengrad',false),
('Svishtov',false),
('Svoge',false),
('Targovishte',false),
('Tervel',false),
('Teteven',false),
('Topolovgrad',false),
('Tran',false),
('Trastenik',false),
('Troyan',false),
('Tryavna',false),
('Tsar Kaloyan',false),
('Tsarevo',false),
('Tutrakan',false),
('Tvarditsa',false),
('Ugarchin',false),
('Valchedram',false),
('Valchi Dol',false),
('Varbitsa',false),
('Varshets',false),
('Veliki Preslav',false),
('Velingrad',false),
('Vetovo',false),
('Vetren',false),
('Vidin',false),
('Vratsa',false),
('Yablanitsa',false),
('Yakoruda',false),
('Yambol',false),
('Zavet',false),
('Zemen',false),
('Zlataritsa',false),
('Zlatitsa',false),
('Zlatograd',false);